Repository mitama-org/mitama, pull requests merged in 2020-10, with the labels that each got.

#99 PRのテンプレート作成
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest

#100 issueのテンプレートを作成しました
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/issue.md
Labels: hacktoberfest

#101 英語版Readmeの作成
  README.en.md
Labels: documentation, hacktoberfest

#102 add
  README.ja.md
  scripts/files/readme/ja.json
  scripts/files/templates/README.jinja.md
  scripts/generate_readme.py
Labels: hacktoberfest, hacktoberfest-accepted

#104 READMEで言語切り替えられるようにする
  README.en.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
